### ISSUE TITLE
Error while adding nested fragments

### ISSUE THREAD

**Issue by h0aX14** [neokree/MaterialNavigationDrawer#102]
Navigation as follows
Drawer section1 clicked->
[Frag1]->[Frag2]->[Frag3]
Navigation drawer opened and again clicked on section1 ->
[Frag1]->[Frag2]->[Frag3]

Now on pressing back key, I get following error in the logcat

     java.lang.IllegalStateException: Fragment already added: Frag1{3c368526 #2 id=0x7f0c005e}
            at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1197)
            at android.support.v4.app.BackStackRecord.popFromBackStack(BackStackRecord.java:915)
            at android.support.v4.app.FragmentManagerImpl.popBackStackState(FragmentManager.java:1541)
            at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:502)
            at android.support.v4.app.FragmentActivity.onBackPressed(FragmentActivity.java:176)
            at android.support.v7.app.ActionBarActivity.onBackPressed(ActionBarActivity.java:298)
            at it.neokree.materialnavigationdrawer.MaterialNavigationDrawer.onBackPressed(MaterialNavigationDrawer.java:534)
            at havan.wallappbase.myapplication.MainActivity.onBackPressed(MainActivity.java:533)
            at android.app.Activity.onKeyUp(Activity.java:2453)
            at android.view.KeyEvent.dispatch(KeyEvent.java:2633)
            at android.app.Activity.dispatchKeyEvent(Activity.java:2704)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2221)
            at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:3918)
            at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3880)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3449)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3502)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3468)
            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3578)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3476)
            at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3635)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3449)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3502)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3468)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3476)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3449)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3502)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3468)
            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3611)
            at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3772)
            at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2208)
            at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1849)
            at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1840)
            at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2185)
            at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
            at android.os.MessageQueue.nativePollOnce(Native Method)
            at android.os.MessageQueue.next(MessageQueue.java:143)
            at android.os.Looper.loop(Looper.java:122)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by neokree** [comment]
please download the new 1.3 alpha from github and use setFragmentChild instead of setFragment.

**Comment by h0aX14** [comment]
Thanks @neokree
