### ISSUE TITLE
singleAccount and NPE

### ISSUE THREAD

**Issue by pawelantczak** [neokree/MaterialNavigationDrawer#140]
Hello.
Single account mode is great. 
I wanted to add fake avatar also, so I used ```setFirstAccountPhoto``` alongside with ```setUsername```.
But, when I click on a other accounts placeholders (not avatar or header itself) there is npe thrown.
```java
java.lang.NullPointerException: Attempt to invoke interface method 'void it.neokree.materialnavigationdrawer.elements.listeners.MaterialAccountListener.onAccountOpening(it.neokree.materialnavigationdrawer.elements.MaterialAccount)' on a null object reference
            at it.neokree.materialnavigationdrawer.MaterialNavigationDrawer$3.onClick(MaterialNavigationDrawer.java:191)
            at android.view.View.performClick(View.java:4756)
            at android.view.View$PerformClick.run(View.java:19749)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5258)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
```

**Comment by pawelantczak** [comment]
This error exists also in demo. 
Clicking one of those placeholders cause npe when single account is enabled.
![NPE](http://i.imgur.com/50YtKEk.png)

**Comment by neokree** [comment]
I have released a bug fix into github now.
