### ISSUE TITLE
NPE on api 10

### ISSUE THREAD

**Issue by pawelantczak** [neokree/MaterialNavigationDrawer#145]
Hello.
There is an NPE error, when you try to use lib on api 10:
```smallestScreenWidthDp``` was introduced in api 13: http://developer.android.com/reference/android/content/res/Configuration.html#SMALLEST_SCREEN_WIDTH_DP_UNDEFINED
```java
java.lang.NoSuchFieldError: android.content.res.Configuration.smallestScreenWidthDp
            at it.neokree.materialnavigationdrawer.util.Utils.getDrawerWidth(Utils.java:37)
            at it.neokree.materialnavigationdrawer.MaterialNavigationDrawer.onCreate(MaterialNavigationDrawer.java:450)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1611)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1663)
            at android.app.ActivityThread.access$1500(ActivityThread.java:117)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:931)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:130)
            at android.app.ActivityThread.main(ActivityThread.java:3683)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:507)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by neokree** [comment]
Fixed

**Comment by privettoli** [comment]
Please close this ticket if it's closed

**Comment by neokree** [comment]
@privettoli it is not closed, in the next release the fix will be avariable. For now only who download the dev module avariable on github could use it.
