### ISSUE TITLE
Multipanel Crash on Galaxy Tab 3

### ISSUE THREAD

**Issue by angelmartz** [neokree/MaterialNavigationDrawer#157]
Hello, when my orientation is landscape, and active multipane support, and navigate between section I get this issue

 java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.ActionBarDrawerToggle.setDrawerIndicatorEnabled(boolean)' on a null object reference
            at it.neokree.materialnavigationdrawer.MaterialNavigationDrawer.onClick(MaterialNavigationDrawer.java:1181)
            at it.neokree.materialnavigationdrawer.elements.MaterialSection.afterClick(MaterialSection.java:445)
            at it.neokree.materialnavigationdrawer.elements.MaterialSection.onTouch(MaterialSection.java:258)
            at android.view.View.dispatchTouchEvent(View.java:8382)

**Comment by neokree** [comment]
I forgot to check if the device uses the multipanesupport when switching between sections or master/child fragments. My fault

**Comment by neokree** [comment]
Fixed in 1.3.2
