### ISSUE TITLE
Crash at setFragment

### ISSUE THREAD

**Issue by mithrann** [neokree/MaterialNavigationDrawer#165]
Hi,
Got this Crash from Library.
![2015-02-07_1506](https://cloud.githubusercontent.com/assets/6015930/6091624/18c681e8-aedb-11e4-8bfb-f6a24b66e8be.png)
![2015-02-07_1507](https://cloud.githubusercontent.com/assets/6015930/6091625/18d4d284-aedb-11e4-9d6c-8f79090121be.png)

And also wondering if i can close the keypad  if its visible on the drawer toggle or closing the navigation drawer. Thanks

**Comment by neokree** [comment]
Wow, nice analytics, what is his name? 
however, library version used?

**Comment by mithrann** [comment]
crashlytics.com Analytics.
Library version -> it.neokree:MaterialNavigationDrawer:1.3

**Comment by neokree** [comment]
I didn't find anything for this type of exception. However it is related to the old version 1.3.

**Comment by rburgst** [comment]
Same problem in 1.3.2

java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.support.v4.app.FragmentManagerImpl.checkStateLoss(SourceFile:1365)
       at android.support.v4.app.FragmentManagerImpl.enqueueAction(SourceFile:1383)
       at android.support.v4.app.BackStackRecord.commitInternal(SourceFile:636)
       at android.support.v4.app.BackStackRecord.commit(SourceFile:615)
       at it.neokree.materialnavigationdrawer.MaterialNavigationDrawer.setFragment(SourceFile:457)
       at it.neokree.materialnavigationdrawer.MaterialNavigationDrawer.onClick(SourceFile:655)
       at com.burgstaller.android.focusgtd.ui.activities.MainActivity.onClick(SourceFile:514)
       at it.neokree.materialnavigationdrawer.MaterialSection.actionUp(SourceFile:359)
       at it.neokree.materialnavigationdrawer.MaterialSection.access$300(SourceFile:27)
       at it.neokree.materialnavigationdrawer.MaterialSection$1.onAnimationEnd(SourceFile:155)
       at at.markushi.ui.RevealColorView$1.onAnimationEnd(SourceFile:105)
       at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1030)
       at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1056)
       at android.animation.ValueAnimator.access$400(ValueAnimator.java:50)
       at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:644)
       at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:660)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
       at android.view.Choreographer.doCallbacks(Choreographer.java:574)
       at android.view.Choreographer.doFrame(Choreographer.java:543)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5086)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)


I am also using fabrics (Crashlytics :) , still looks the same

**Comment by rburgst** [comment]
so to me this looks like a race condition. the activity got stopped while the ripple animation was running. You should check the state in `it.neokree.materialnavigationdrawer.MaterialSection$1.onAnimationEnd(SourceFile:155)`

**Comment by rburgst** [comment]
My bad, this crash was still with 1.2.9 however, I see that the code in MaterialSection has not changed and therefore, the bug will most likely also exist in 1.3.2

**Comment by rburgst** [comment]
yes, got it with 1.3.2 too

    java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
           at android.support.v4.app.FragmentManagerImpl.checkStateLoss(SourceFile:1365)
           at android.support.v4.app.FragmentManagerImpl.enqueueAction(SourceFile:1383)
           at android.support.v4.app.BackStackRecord.commitInternal(SourceFile:636)
           at android.support.v4.app.BackStackRecord.commit(SourceFile:615)
           at it.neokree.materialnavigationdrawer.MaterialNavigationDrawer.setFragment(SourceFile:1019)
           at it.neokree.materialnavigationdrawer.MaterialNavigationDrawer.setFragment(SourceFile:980)
           at it.neokree.materialnavigationdrawer.MaterialNavigationDrawer.onClick(SourceFile:1264)
           at com.burgstaller.android.focusgtd.ui.activities.MainActivity.onClick(SourceFile:513)
           at it.neokree.materialnavigationdrawer.elements.MaterialSection.afterClick(SourceFile:472)
           at it.neokree.materialnavigationdrawer.elements.MaterialSection.onClick(SourceFile:279)
           at android.view.View.performClick(View.java:4756)
           at com.balysv.materialripple.MaterialRippleLayout$PerformClickEvent.run(SourceFile:640)
           at com.balysv.materialripple.MaterialRippleLayout$3.onAnimationEnd(SourceFile:328)
           at android.animation.AnimatorSet.cancel(AnimatorSet.java:327)
           at com.balysv.materialripple.MaterialRippleLayout.cancelAnimations(SourceFile:355)
           at com.balysv.materialripple.MaterialRippleLayout.startRipple(SourceFile:318)
           at com.balysv.materialripple.MaterialRippleLayout.onTouchEvent(SourceFile:256)
           at android.view.View.dispatchTouchEvent(View.java:8389)
           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2424)
           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2158)
           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2452)
           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
           at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2314)
           at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1692)
           at android.app.Activity.dispatchTouchEvent(Activity.java:2739)
           at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2275)
           at android.view.View.dispatchPointerEvent(View.java:8579)
           at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4146)
           at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4012)
           at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3569)
           at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3622)
           at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3588)
           at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3701)
           at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3596)
           at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3758)
           at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3569)
           at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3622)
           at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3588)
           at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3596)
           at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3569)
           at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5860)
           at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5834)
           at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5805)
           at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5950)
           at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
           at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
           at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
           at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5921)
           at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:5973)
           at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
           at android.view.Choreographer.doCallbacks(Choreographer.java:580)
           at android.view.Choreographer.doFrame(Choreographer.java:548)
           at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
           at android.os.Handler.handleCallback(Handler.java:739)
           at android.os.Handler.dispatchMessage(Handler.java:95)
           at android.os.Looper.loop(Looper.java:135)
           at android.app.ActivityThread.main(ActivityThread.java:5240)
           at java.lang.reflect.Method.invoke(Method.java)
           at java.lang.reflect.Method.invoke(Method.java:372)
           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by rburgst** [comment]
same crash in 1.3.3

    java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
           at android.support.v4.app.FragmentManagerImpl.checkStateLoss(SourceFile:1375)
           at android.support.v4.app.FragmentManagerImpl.enqueueAction(SourceFile:1393)
           at android.support.v4.app.BackStackRecord.commitInternal(SourceFile:636)
           at android.support.v4.app.BackStackRecord.commit(SourceFile:615)
           at it.neokree.materialnavigationdrawer.MaterialNavigationDrawer.setFragment(SourceFile:1085)
           at it.neokree.materialnavigationdrawer.MaterialNavigationDrawer.setFragment(SourceFile:1046)
           at it.neokree.materialnavigationdrawer.MaterialNavigationDrawer.init(SourceFile:68)
           at it.neokree.materialnavigationdrawer.MaterialNavigationDrawer$7.onDrawerClosed(SourceFile:560)
           at android.support.v4.widget.DrawerLayout.dispatchOnDrawerClosed(SourceFile:646)
           at android.support.v4.widget.DrawerLayout.updateDrawerState(SourceFile:626)
           at android.support.v4.widget.DrawerLayout$ViewDragCallback.onViewDragStateChanged(SourceFile:1653)
           at android.support.v4.widget.ViewDragHelper.setDragState(SourceFile:874)
           at android.support.v4.widget.ViewDragHelper$2.run(SourceFile:335)
           at android.os.Handler.handleCallback(Handler.java:733)
           at android.os.Handler.dispatchMessage(Handler.java:95)
           at android.os.Looper.loop(Looper.java:157)
           at android.app.ActivityThread.main(ActivityThread.java:5335)
           at java.lang.reflect.Method.invokeNative(Method.java)
           at java.lang.reflect.Method.invoke(Method.java:515)
           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
           at dalvik.system.NativeStart.main(NativeStart.java)
