### ISSUE TITLE
native typeface cannot be made

### ISSUE THREAD

**Issue by makhazzan** [neokree/MaterialNavigationDrawer#168]
FATAL EXCEPTION: main
 Process: it.neokree.example, PID: 28339
 java.lang.RuntimeException: Unable to start activity ComponentInfo{it.neokree.example/it.neokree.example.light.MockedAccount}: java.lang.RuntimeException: native typeface cannot be made
 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2212)
 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2271)
 	at android.app.ActivityThread.access$800(ActivityThread.java:144)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
 	at android.os.Handler.dispatchMessage(Handler.java:102)
 	at android.os.Looper.loop(Looper.java:136)
 	at android.app.ActivityThread.main(ActivityThread.java:5146)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:515)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
 	at dalvik.system.NativeStart.main(Native Method)
 Caused by: java.lang.RuntimeException: native typeface cannot be made
 	at android.graphics.Typeface.<init>(Typeface.java:175)
 	at android.graphics.Typeface.createFromAsset(Typeface.java:149)
 	at it.neokree.materialnavigationdrawer.util.TypefaceManager$Typefaces.get(TypefaceManager.java:51)
 	at it.neokree.materialnavigationdrawer.util.TypefaceManager.getTypeface(TypefaceManager.java:37)
 	at it.neokree.materialnavigationdrawer.util.TypefaceManager.getRobotoMedium(TypefaceManager.java:31)
 	at it.neokree.materialnavigationdrawer.MaterialNavigationDrawer.onCreate(MaterialNavigationDrawer.java:407)
 	at android.app.Activity.performCreate(Activity.java:5231)
 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)
 	... 11 more

**Comment by neokree** [comment]
api version used and device tested?

**Comment by ismben** [comment]
i'm having the same issue with Nexus S api 16

**Comment by alex-soft-r** [comment]
I had the same problem.
Just copy folder "assets" with fonts from "MaterialNavigationDrawerModule" tinto root of your project.

**Comment by ismben** [comment]
thanks, that solved my problem
