### ISSUE TITLE
smallestScreenWidthDp

### ISSUE THREAD

**Issue by RicardoRB** [neokree/MaterialNavigationDrawer#169]
Hi! I was testing your library and when I compiled it in my small device (Samsung galaxy mini) this throw me this error:

```java
java.lang.NoSuchFieldError: android.content.res.Configuration.smallestScreenWidthDp
            at it.neokree.materialnavigationdrawer.util.Utils.getDrawerWidth(Utils.java:37)
            at it.neokree.materialnavigationdrawer.MaterialNavigationDrawer.onCreate(MaterialNavigationDrawer.java:450)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1722)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1784)
            at android.app.ActivityThread.access$1500(ActivityThread.java:123)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:939)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:130)
            at android.app.ActivityThread.main(ActivityThread.java:3835)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:507)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
            at dalvik.system.NativeStart.main(Native Method)
```

Is this an error or can't I use this library for small devices?

**Comment by neokree** [comment]
What library version are you using? 

This problem is related to the <code>smallestScreenWithDp</code> resource. I haven't checked correctly the api for 1.3, and it throw this error. 
The developement version on github have a bug fix for this.

**Comment by RicardoRB** [comment]
Oh I did not see it, so sorry. I was using 1.3 version. Thank you very much!
