### ISSUE TITLE
create dialog in addAccountSection  error

### ISSUE THREAD

**Issue by dat0106** [neokree/MaterialNavigationDrawer#251]
this.addAccountSection(newSection(getString(R.string.add_profile), R.drawable.ic_action_content_add, new MaterialSectionListener() {
            @Override
            public void onClick(MaterialSection materialSection) {
                AlertDialog.Builder builder = new AlertDialog.Builder(BlueScreenFilter.this);

                LayoutInflater inflater = BlueScreenFilter.this.getLayoutInflater();

                builder.setTitle(R.string.add_profile);
                builder.setCancelable(true);
                // Inflate and set the layout for the dialog
                // Pass null as the parent view because its going in the dialog layout
                builder.setView(inflater.inflate(R.layout.dialog_add_profile, null))
                        // Add action buttons
                        .setPositiveButton(android.R.string.ok, new DialogInterface.OnClickListener() {
                            @Override
                            public void onClick(DialogInterface dialog, int id) {
                                // sign in the user ...
                                dialog.cancel();
                            }
                        })
                        .setNegativeButton(android.R.string.cancel, new DialogInterface.OnClickListener() {
                            public void onClick(DialogInterface dialog, int id) {
                                dialog.cancel();
                            }
                        });

                builder.show();
            }
        }));

this will throw error 
 java.lang.NullPointerException: Attempt to invoke virtual method 'int it.neokree.materialnavigationdrawer.elements.Element.getType()' on a null object reference
            at it.neokree.materialnavigationdrawer.MaterialNavigationDrawer.onSaveInstanceState(MaterialNavigationDrawer.java:932)
            at android.app.Activity.performSaveInstanceState(Activity.java:1297)
            at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1272)
            at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:3954)
            at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3365)
            at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3421)
            at android.app.ActivityThread.access$1200(ActivityThread.java:147)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1325)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5256)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)

NOTE:  addSection is OK

**Comment by dat0106** [comment]
UPDATE: we need addSection at least 1 time before addAccountSection
