### ISSUE TITLE
Out of memory Error 

### ISSUE THREAD

**Issue by MichaelGirgis** [neokree/MaterialNavigationDrawer#282]
This track appeared to me from library:
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:300)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 65536012 byte allocation with 30360784 free bytes and 28MB until OOM
at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:609)
at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:467)
at it.neokree.materialnavigationdrawer.util.Utils.resizeBitmapFromResource(Utils.java:127)
at it.neokree.materialnavigationdrawer.elements.MaterialAccount$ResizeBackgroundResource.doInBackground(MaterialAccount.java:250)
at it.neokree.materialnavigationdrawer.elements.MaterialAccount$ResizeBackgroundResource.doInBackground(MaterialAccount.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 4 more

**Comment by nicolasheraly** [comment]
Same bug for me. App crashed !

java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:304)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
       at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:591)
       at it.neokree.materialnavigationdrawer.util.Utils.resizeBitmap(Utils.java:131)
       at it.neokree.materialnavigationdrawer.elements.MaterialAccount$ResizePhotoBitmap.doInBackground(MaterialAccount.java:229)
       at it.neokree.materialnavigationdrawer.elements.MaterialAccount$ResizePhotoBitmap.doInBackground(MaterialAccount.java:222)
       at android.os.AsyncTask$2.call(AsyncTask.java:292)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecu
