### ISSUE TITLE
setFragment(Fragment fragment, String title) cause IllegalStateException

### ISSUE THREAD

**Issue by evasyuk** [neokree/MaterialNavigationDrawer#302]
I need to replace Fragment from itself with itemOnClick() and seems that something is going wrong. Using setFragmentChild(Fragment fragment,String title); cause the same exception.

05-27 21:44:49.770    2818-2818/com.daimajia.swipelayout E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
            at android.view.ViewGroup.addViewInner(ViewGroup.java:3378)
            at android.view.ViewGroup.addView(ViewGroup.java:3249)
            at android.view.ViewGroup.addView(ViewGroup.java:3194)
            at android.view.ViewGroup.addView(ViewGroup.java:3170)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:970)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
            at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:458)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4745)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)

Any suggestions how can I fix that?

**Comment by evasyuk** [comment]
My bad - problem was in my code
