### ISSUE TITLE
Error IndexOutOfBoundsException

### ISSUE THREAD

**Issue by nulijiabei** [neokree/MaterialNavigationDrawer#314]
06-29 19:46:29.980    9266-9266/com.danoo.nljb.surpass2 E/InputEventReceiver﹕ Exception dispatching input event.
06-29 19:46:29.980    9266-9266/com.danoo.nljb.surpass2 E/MessageQueue-JNI﹕ Exception in MessageQueue callback: handleReceiveCallback
06-29 19:46:30.000    9266-9266/com.danoo.nljb.surpass2 E/MessageQueue-JNI﹕ java.lang.IndexOutOfBoundsException
            at java.util.LinkedList.get(LinkedList.java:519)
            at it.neokree.materialnavigationdrawer.MaterialNavigationDrawer$4.onClick(MaterialNavigationDrawer.java:235)
            at it.neokree.materialnavigationdrawer.MaterialNavigationDrawer$5.onClick(MaterialNavigationDrawer.java:333)
            at it.neokree.materialnavigationdrawer.elements.MaterialSection.afterClick(MaterialSection.java:472)
            at it.neokree.materialnavigationdrawer.elements.MaterialSection.onTouch(MaterialSection.java:264)
            at android.view.View.dispatchTouchEvent(View.java:7723)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2212)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1945)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)

// ...............//

public class MyNavigationDrawer extends MaterialNavigationDrawer implements MaterialAccountListener {

    // User
    private User user = null;

    // Account
    private MaterialAccount x86Account = null;
    private MaterialAccount androidAccount = null;

    // Section
    private ArrayList<MaterialSection> x86ArraySection = new ArrayList<MaterialSection>();
    private ArrayList<MaterialSection> androidArraySection = new ArrayList<MaterialSection>();

    // settings
    private MaterialSection settingsSection = null;

    @Override
    public void init(Bundle bundle) {

        Intent intent = getIntent();
        user = (User) intent.getSerializableExtra("USER_INFO");
        Log.i("INFO", user.getUsername());

        // Account
        x86Account = new MaterialAccount(this.getResources(), "x86", user.getUsername(), R.drawable.photo, R.drawable.bamboo);
        androidAccount = new MaterialAccount(this.getResources(), "android", user.getUsername(), R.drawable.photo2, R.drawable.mat2);

        // x86 sections
        x86ArraySection.add(0, newSection("X86-A", R.drawable.ic_mic_white_24dp, new SoftwarePreference()).setSectionColor(Color.parseColor("#2B6CB8")));
        x86ArraySection.add(1, newSection("X86-B", R.drawable.ic_mic_white_24dp, new SoftwarePreference()).setSectionColor(Color.parseColor("#2B6CB8")));
        x86ArraySection.add(2, newSection("X86-B", R.drawable.ic_mic_white_24dp, new SoftwarePreference()).setSectionColor(Color.parseColor("#2B6CB8")));
        x86ArraySection.add(3, newSection("X86-B", R.drawable.ic_mic_white_24dp, new SoftwarePreference()).setSectionColor(Color.parseColor("#2B6CB8")));

        // android sections
        androidArraySection.add(0, newSection("Android-A", R.drawable.ic_mic_white_24dp, new SoftwarePreference()).setSectionColor(Color.parseColor("#2B6CB8")));
        androidArraySection.add(1, newSection("Android-A", R.drawable.ic_mic_white_24dp, new SoftwarePreference()).setSectionColor(Color.parseColor("#2B6CB8")));
        androidArraySection.add(2, newSection("Android-A", R.drawable.ic_mic_white_24dp, new SoftwarePreference()).setSectionColor(Color.parseColor("#2B6CB8")));
        androidArraySection.add(3, newSection("Android-A", R.drawable.ic_mic_white_24dp, new SoftwarePreference()).setSectionColor(Color.parseColor("#2B6CB8")));

        // settings sections
        settingsSection = newSection("setting", R.drawable.ic_settings_black_24dp, new Intent(this, SettingsActivity.class));

        // ...
        switch (user.getAuthority()) {
            case 1000: // admin
                addAccount(x86Account);
                addAccount(androidAccount);
                for (int i = 0; i < x86ArraySection.size(); i++) {
                    addSection(x86ArraySection.get(i));
                }
                break;
            case 1001: // x86
                addAccount(x86Account);
                for (int i = 0; i < x86ArraySection.size(); i++) {
                    addSection(x86ArraySection.get(i));
                }
                break;
            case 1002: // android
                addAccount(androidAccount);
                for (int i = 0; i < androidArraySection.size(); i++) {
                    addSection(androidArraySection.get(i));
                }
                break;
        }

        // create bottom section
        this.addBottomSection(settingsSection);

        // set listener
        this.setAccountListener(this);

    }

    @Override
    public void onAccountOpening(MaterialAccount materialAccount) {
    }

    @Override
    public void onChangeAccount(final MaterialAccount materialAccount) {
        Log.i("INFO", materialAccount.getTitle());
        if (materialAccount.getTitle().toString().equals("x86")) {
            for (int i = 0; i < androidArraySection.size(); i++) {
                removeSection(androidArraySection.get(i));
            }
            for (int i = 0; i < x86ArraySection.size(); i++) {
                removeSection(x86ArraySection.get(i));
            }
            for (int i = 0; i < x86ArraySection.size(); i++) {
                addSection(x86ArraySection.get(i));
            }
        }
        if (materialAccount.getTitle().toString().equals("android")) {
            for (int i = 0; i < androidArraySection.size(); i++) {
                removeSection(androidArraySection.get(i));
            }
            for (int i = 0; i < x86ArraySection.size(); i++) {
                removeSection(x86ArraySection.get(i));
            }
            for (int i = 0; i < androidArraySection.size(); i++) {
                addSection(androidArraySection.get(i));
            }
        }
    }

// .................... //

**Comment by nulijiabei** [comment]
public void removeSection(MaterialSection section) {

        // ...
        Element element = findElementBySection(section);
        if (element != null) {
            elementsList.remove(element);
        }

        // remove section from section list and recalculate positions
        sectionList.remove(section);

        // removes section view from the drawer
        sections.removeView(section.getView());
    }
