### ISSUE TITLE
OutOfMemory exception in NavigationDrawer Bitmap

### ISSUE THREAD

**Issue by mohd-bh** [neokree/MaterialNavigationDrawer#74]
I have a login activity on my app, and when the user logs in, it goes to the main activity which has the navigation drawer. The problem occurs when the user close the app and re-open it to main activity, I get out of memory exception in the nav drawer. here are the details: 

````
01-03 16:06:47.295    1187-1187/itcs.mohd.socialy E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: itcs.mohd.socialy, PID: 1187
    java.lang.OutOfMemoryError
            at android.graphics.Bitmap.nativeCreate(Native Method)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:810)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:787)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:754)
            at it.neokree.materialnavigationdrawer.MaterialAccount.getCroppedBitmap(MaterialAccount.java:123)
            at it.neokree.materialnavigationdrawer.MaterialAccount.getCircularPhoto(MaterialAccount.java:94)
            at it.neokree.materialnavigationdrawer.MaterialNavigationDrawer.notifyAccountDataChanged(MaterialNavigationDrawer.java:742)
            at it.neokree.materialnavigationdrawer.MaterialNavigationDrawer.onCreate(MaterialNavigationDrawer.java:336)
            at android.app.Activity.performCreate(Activity.java:5231)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2271)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5146)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
            at dalvik.system.NativeStart.main(Native Method)
````

**Comment by neokree** [comment]
please I suggest to close this issue referencing to the main issue #60
